using Steam.KeyValues;
using System;
using System.Collections.Generic;

namespace Steam.Local.Models
{
    internal class LibraryFolders
    {
        [KeyValueProperty]
        public DateTimeOffset TimeNextStatsReport { get; set; }
        [KeyValueProperty]
        public long ContentStatsID { get; set; }
        [KeyValueAutogenerated]
        private List<string> Folders { get; set; }
    }
}
