using System;

namespace Steam.KeyValues
{
    /// <summary>
    /// Instructs the <see cref="KeyValueSerializer"/> to use this as a collection for autogenerated keys
    /// </summary>
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, AllowMultiple = false)]
    public class KeyValueAutogeneratedAttribute : KeyValueContainerAttribute
    {
    }
}
