using System;

namespace Steam.KeyValues
{
    /// <summary>
    /// Instructs the <see cref="KeyValueSerializer"/> to deserialize properties with no matching class member into the specified collection and write values during serialization
    /// </summary>
    public class KeyValueExtensionDataAttribute : Attribute
    {
        /// <summary>
        /// Instructs the <see cref="KeyValueSerializer"/> to also deserialize and serialize properties with autogenerated key names
        /// </summary>
        public bool IncludeAutogeneratedKeys { get; set; }
    }
}
